service: otot #Name of your App

provider:
 name: aws
 runtime: nodejs12.x # Node JS version
 memorySize: 128
 timeout: 15
 stage: dev
 region: us-east-2 # AWS region

functions:
 api:
   handler: lambda.handler #consider changing to index.handler since it is our entry point
   events:
     - http: ANY {proxy+}
     - http: ANY /
   environment:
    DB_SOURCE: 'atlas'